language: ruby

rvm:
  - 2.1.1

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec

branches:
  only:
    - master

before_script:
  - psql -c 'create database spokenvote_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - rake db:test_prep

bundler_args: --without development

notifications:
  email:
    recipients:
      - spokenvote-dev@googlegroups.com
    on_success: change
    on_failure: always
