language: ruby

rvm:
  - 1.9.3

branches:
  only:
    - master

script:
  - bundle exec rake db:create:all
  - RAILS_ENV=test bundle exec rake db:test_prep
  - bundle exec rspec

before_script:
  - psql -c 'create database spokenvote_test;' -U postgres
  - cp config/database.travis.yml config/database.yml

bundler_args: --without development
