login: &login
  adapter: postgresql
  host: localhost
  username: postgres
  password: diplomat1

development:
  database: typo_dev
  <<: *login

test:
  database: typo_tests
  <<: *login

production:
  database: typo_production
  <<: *login
