login: &login
  adapter: postgresql
  host: localhost
  username: postgres
  password: diplomat1

development:
  database: spokenvote_dev
  <<: *login

test:
  database: spokenvote_tests
  <<: *login

production:
  database: spokenvote_production
  <<: *login
